name: line_sign_in
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

flutter:
  plugin:
    androidPackage: com.najeira.linesignin
    pluginClass: LineSignInPlugin

dependencies:
  flutter:
    sdk: flutter
