name: facebook_sign_in
description: A Flutter plugin for Facebook Sign In.
version: 0.0.1
author: najeira
homepage: https://github.com/najeira/flutter-plugins

flutter:
  plugin:
    androidPackage: com.najeira.facebooksignin
    pluginClass: FacebookSignInPlugin

dependencies:
  flutter:
    sdk: flutter
